/**
 * QUIT THE DISTRACTS — MEGA BLOCKLIST v2
 * 200+ real ad networks, trackers, fingerprinters, data brokers
 * Sources: EasyList, EasyPrivacy, uBlock Origin, Peter Lowe's list, Steven Black's hosts
 */
window.BLOCKLIST = {
  adNetworks: [
    { domain: "doubleclick.net",             name: "Google DoubleClick",           type: "Ad Network",      risk: "high" },
    { domain: "googlesyndication.com",       name: "Google AdSense",               type: "Ad Network",      risk: "high" },
    { domain: "googleadservices.com",        name: "Google Ad Services",           type: "Ad Network",      risk: "high" },
    { domain: "adnxs.com",                  name: "AppNexus / Xandr",             type: "Ad Network",      risk: "high" },
    { domain: "adnxs-simple.com",           name: "AppNexus Simple",              type: "Ad Network",      risk: "high" },
    { domain: "moatads.com",                name: "Oracle Moat",                  type: "Ad Measurement",  risk: "medium" },
    { domain: "moatpixel.com",              name: "Moat Pixel",                   type: "Ad Measurement",  risk: "medium" },
    { domain: "taboola.com",                name: "Taboola",                      type: "Content Ads",     risk: "high" },
    { domain: "cdn.taboola.com",            name: "Taboola CDN",                  type: "Content Ads",     risk: "high" },
    { domain: "trc.taboola.com",            name: "Taboola Reco",                 type: "Content Ads",     risk: "high" },
    { domain: "outbrain.com",               name: "Outbrain",                     type: "Content Ads",     risk: "high" },
    { domain: "widgets.outbrain.com",       name: "Outbrain Widgets",             type: "Content Ads",     risk: "high" },
    { domain: "revcontent.com",             name: "RevContent",                   type: "Content Ads",     risk: "high" },
    { domain: "criteo.com",                 name: "Criteo",                       type: "Retargeting",     risk: "high" },
    { domain: "criteo.net",                 name: "Criteo Network",               type: "Retargeting",     risk: "high" },
    { domain: "static.criteo.net",          name: "Criteo Static",                type: "Retargeting",     risk: "high" },
    { domain: "rubiconproject.com",         name: "Magnite (Rubicon)",            type: "Programmatic",    risk: "high" },
    { domain: "fastlane.rubiconproject.com",name: "Rubicon Fastlane",             type: "Programmatic",    risk: "high" },
    { domain: "pubmatic.com",               name: "PubMatic",                     type: "Programmatic",    risk: "high" },
    { domain: "ads.pubmatic.com",           name: "PubMatic Ads",                 type: "Programmatic",    risk: "high" },
    { domain: "openx.net",                  name: "OpenX",                        type: "Programmatic",    risk: "high" },
    { domain: "us-u.openx.net",             name: "OpenX US",                     type: "Programmatic",    risk: "high" },
    { domain: "advertising.com",            name: "Yahoo Advertising",            type: "Ad Network",      risk: "high" },
    { domain: "media.net",                  name: "Media.net",                    type: "Ad Network",      risk: "high" },
    { domain: "33across.com",               name: "33Across",                     type: "Ad Network",      risk: "medium" },
    { domain: "adroll.com",                name: "AdRoll",                       type: "Retargeting",     risk: "high" },
    { domain: "d.adroll.com",              name: "AdRoll Pixel",                 type: "Retargeting",     risk: "high" },
    { domain: "amazon-adsystem.com",       name: "Amazon DSP",                   type: "Ad Network",      risk: "medium" },
    { domain: "aax-us-east.amazon-adsystem.com", name: "Amazon AAX",             type: "Ad Network",      risk: "medium" },
    { domain: "adsafeprotected.com",       name: "IAS Ad Safety",                type: "Ad Measurement",  risk: "medium" },
    { domain: "smartadserver.com",         name: "Smart AdServer",               type: "Programmatic",    risk: "high" },
    { domain: "yieldmo.com",               name: "Yieldmo",                      type: "Ad Network",      risk: "high" },
    { domain: "gumgum.com",                name: "GumGum",                       type: "Contextual Ads",  risk: "medium" },
    { domain: "triplelift.com",            name: "TripleLift",                   type: "Native Ads",      risk: "high" },
    { domain: "3lift.com",                 name: "TripleLift CDN",               type: "Native Ads",      risk: "high" },
    { domain: "indexexchange.com",         name: "Index Exchange",               type: "Programmatic",    risk: "high" },
    { domain: "sharethrough.com",          name: "Sharethrough",                 type: "Native Ads",      risk: "high" },
    { domain: "bidswitch.net",             name: "BidSwitch",                    type: "Programmatic",    risk: "high" },
    { domain: "sovrn.com",                 name: "Sovrn",                        type: "Ad Network",      risk: "high" },
    { domain: "lijit.com",                 name: "Lijit (Sovrn)",                type: "Ad Network",      risk: "high" },
    { domain: "undertone.com",             name: "Undertone",                    type: "Ad Network",      risk: "high" },
    { domain: "spotxchange.com",           name: "SpotX",                        type: "Video Ads",       risk: "high" },
    { domain: "spotx.tv",                  name: "SpotX TV",                     type: "Video Ads",       risk: "high" },
    { domain: "springserve.com",           name: "SpringServe",                  type: "Video Ads",       risk: "high" },
    { domain: "freewheel.tv",              name: "FreeWheel",                    type: "Video Ads",       risk: "high" },
    { domain: "fwmrm.net",                 name: "FreeWheel MRM",                type: "Video Ads",       risk: "high" },
    { domain: "contextweb.com",            name: "Pulsepoint",                   type: "Ad Network",      risk: "high" },
    { domain: "casalemedia.com",           name: "Index Exchange (Casale)",      type: "Programmatic",    risk: "high" },
    { domain: "teads.tv",                  name: "Teads",                        type: "Video Ads",       risk: "high" },
    { domain: "a.teads.tv",                name: "Teads CDN",                    type: "Video Ads",       risk: "high" },
    { domain: "adsrvr.org",                name: "The Trade Desk",               type: "DSP",             risk: "high" },
    { domain: "ads.yahoo.com",             name: "Yahoo Ads",                    type: "Ad Network",      risk: "high" },
    { domain: "ads.linkedin.com",          name: "LinkedIn Ads",                 type: "Social Ads",      risk: "medium" },
    { domain: "ads.twitter.com",           name: "Twitter/X Ads",                type: "Social Ads",      risk: "medium" },
    { domain: "static.ads-twitter.com",    name: "Twitter Ads Static",           type: "Social Ads",      risk: "medium" },
    { domain: "sc-static.net",             name: "Snapchat Ads",                 type: "Social Ads",      risk: "medium" },
    { domain: "tr.snapchat.com",           name: "Snap Pixel",                   type: "Social Tracker",  risk: "high" },
    { domain: "analytics.tiktok.com",      name: "TikTok Analytics",             type: "Social Tracker",  risk: "high" },
    { domain: "ads.pinterest.com",         name: "Pinterest Ads",                type: "Social Ads",      risk: "medium" },
    { domain: "ct.pinterest.com",          name: "Pinterest Conversion",         type: "Social Tracker",  risk: "medium" },
    { domain: "mgid.com",                  name: "MGID",                         type: "Content Ads",     risk: "high" },
    { domain: "adform.net",                name: "Adform",                       type: "Ad Network",      risk: "high" },
    { domain: "adform.com",                name: "Adform",                       type: "Ad Network",      risk: "high" },
    { domain: "mediavine.com",             name: "Mediavine",                    type: "Ad Network",      risk: "medium" },
    { domain: "ezoic.com",                 name: "Ezoic",                        type: "Ad Network",      risk: "medium" },
    { domain: "adthrive.com",              name: "AdThrive / Raptive",           type: "Ad Network",      risk: "medium" },
    { domain: "raptive.com",               name: "Raptive",                      type: "Ad Network",      risk: "medium" },
    { domain: "propellerads.com",          name: "PropellerAds",                 type: "Ad Network",      risk: "high" },
    { domain: "popcash.net",               name: "PopCash",                      type: "Pop Ads",         risk: "high" },
    { domain: "popads.net",                name: "PopAds",                       type: "Pop Ads",         risk: "high" },
    { domain: "valueclick.com",            name: "Conversant/ValueClick",        type: "Affiliate Ads",   risk: "high" },
    { domain: "advertising.amazon.com",    name: "Amazon Advertising",           type: "Ad Network",      risk: "medium" },
    { domain: "snap.licdn.com",            name: "LinkedIn Insight Tag",         type: "Social Tracker",  risk: "medium" },
    { domain: "yldbt.com",                 name: "Yieldbird",                    type: "Ad Network",      risk: "high" },
    { domain: "exponential.com",           name: "Exponential",                  type: "Ad Network",      risk: "high" },
    { domain: "technoratimedia.com",       name: "Technorati Media",             type: "Ad Network",      risk: "high" },
  ],

  trackers: [
    { domain: "google-analytics.com",       name: "Google Analytics (UA)",       type: "Analytics",        risk: "medium" },
    { domain: "analytics.google.com",       name: "Google Analytics 4",          type: "Analytics",        risk: "medium" },
    { domain: "googletagmanager.com",       name: "Google Tag Manager",          type: "Tag Manager",      risk: "medium" },
    { domain: "googletagservices.com",      name: "Google Tag Services",         type: "Tag Manager",      risk: "medium" },
    { domain: "facebook.net",              name: "Facebook Pixel",              type: "Social Tracker",   risk: "high" },
    { domain: "connect.facebook.net",      name: "Facebook Connect",            type: "Social Tracker",   risk: "high" },
    { domain: "graph.facebook.com",        name: "Facebook Graph API",          type: "Social Tracker",   risk: "high" },
    { domain: "analytics.twitter.com",     name: "Twitter Analytics",           type: "Social Tracker",   risk: "medium" },
    { domain: "t.co",                      name: "Twitter Link Tracker",        type: "Link Tracker",     risk: "medium" },
    { domain: "hotjar.com",                name: "Hotjar",                      type: "Session Replay",   risk: "high" },
    { domain: "static.hotjar.com",         name: "Hotjar Static",               type: "Session Replay",   risk: "high" },
    { domain: "vars.hotjar.com",           name: "Hotjar Vars",                 type: "Session Replay",   risk: "high" },
    { domain: "mouseflow.com",             name: "Mouseflow",                   type: "Session Replay",   risk: "high" },
    { domain: "fullstory.com",             name: "FullStory",                   type: "Session Replay",   risk: "high" },
    { domain: "rs.fullstory.com",          name: "FullStory RS",                type: "Session Replay",   risk: "high" },
    { domain: "logrocket.com",             name: "LogRocket",                   type: "Session Replay",   risk: "high" },
    { domain: "smartlook.com",             name: "Smartlook",                   type: "Session Replay",   risk: "high" },
    { domain: "segment.io",               name: "Segment",                     type: "CDP",              risk: "medium" },
    { domain: "segment.com",              name: "Segment Analytics",           type: "CDP",              risk: "medium" },
    { domain: "cdn.segment.com",          name: "Segment CDN",                 type: "CDP",              risk: "medium" },
    { domain: "api.segment.io",           name: "Segment API",                 type: "CDP",              risk: "medium" },
    { domain: "mixpanel.com",             name: "Mixpanel",                    type: "Analytics",        risk: "medium" },
    { domain: "amplitude.com",            name: "Amplitude",                   type: "Analytics",        risk: "medium" },
    { domain: "cdn.amplitude.com",        name: "Amplitude CDN",               type: "Analytics",        risk: "medium" },
    { domain: "api2.amplitude.com",       name: "Amplitude API",               type: "Analytics",        risk: "medium" },
    { domain: "heap.io",                  name: "Heap Analytics",              type: "Analytics",        risk: "medium" },
    { domain: "heapanalytics.com",        name: "Heap",                        type: "Analytics",        risk: "medium" },
    { domain: "intercom.io",              name: "Intercom",                    type: "CRM Tracker",      risk: "medium" },
    { domain: "intercom.com",             name: "Intercom",                    type: "Chat/Tracker",     risk: "medium" },
    { domain: "widget.intercom.io",       name: "Intercom Widget",             type: "CRM Tracker",      risk: "medium" },
    { domain: "hubspot.com",              name: "HubSpot",                     type: "CRM Tracker",      risk: "medium" },
    { domain: "hs-scripts.com",           name: "HubSpot Scripts",             type: "CRM Tracker",      risk: "medium" },
    { domain: "hs-analytics.net",         name: "HubSpot Analytics",           type: "CRM Tracker",      risk: "medium" },
    { domain: "hsforms.com",              name: "HubSpot Forms",               type: "CRM Tracker",      risk: "low" },
    { domain: "marketo.net",              name: "Marketo",                     type: "Marketing",        risk: "medium" },
    { domain: "mktoresp.com",             name: "Marketo Resp",                type: "Marketing",        risk: "medium" },
    { domain: "pardot.com",               name: "Salesforce Pardot",           type: "Marketing",        risk: "medium" },
    { domain: "pi.pardot.com",            name: "Pardot Pixel",                type: "Marketing",        risk: "medium" },
    { domain: "optimizely.com",           name: "Optimizely",                  type: "A/B Testing",      risk: "low" },
    { domain: "cdn.optimizely.com",       name: "Optimizely CDN",              type: "A/B Testing",      risk: "low" },
    { domain: "newrelic.com",             name: "New Relic",                   type: "APM",              risk: "low" },
    { domain: "nr-data.net",              name: "New Relic Data",              type: "APM",              risk: "low" },
    { domain: "bam.nr-data.net",          name: "New Relic BAM",               type: "APM",              risk: "low" },
    { domain: "datadoghq.com",            name: "Datadog",                     type: "APM",              risk: "low" },
    { domain: "quantserve.com",           name: "Quantcast",                   type: "Audience",         risk: "high" },
    { domain: "scorecardresearch.com",    name: "Comscore",                    type: "Audience",         risk: "high" },
    { domain: "chartbeat.com",            name: "Chartbeat",                   type: "Analytics",        risk: "medium" },
    { domain: "static.chartbeat.com",     name: "Chartbeat Static",            type: "Analytics",        risk: "medium" },
    { domain: "omtrdc.net",               name: "Adobe Analytics",             type: "Analytics",        risk: "medium" },
    { domain: "demdex.net",               name: "Adobe Audience Manager",      type: "DMP",              risk: "high" },
    { domain: "2o7.net",                  name: "Adobe Measurement",           type: "Analytics",        risk: "medium" },
    { domain: "adobedtm.com",             name: "Adobe Launch/DTM",            type: "Tag Manager",      risk: "medium" },
    { domain: "krxd.net",                 name: "Krux (Salesforce DMP)",       type: "DMP",              risk: "high" },
    { domain: "bluekai.com",              name: "Oracle BlueKai",              type: "DMP",              risk: "high" },
    { domain: "addthis.com",              name: "AddThis",                     type: "Social Share",     risk: "high" },
    { domain: "sharethis.com",            name: "ShareThis",                   type: "Social Share",     risk: "high" },
    { domain: "disqus.com",               name: "Disqus",                      type: "Comments",         risk: "medium" },
    { domain: "braze.com",                name: "Braze",                       type: "Push/Marketing",   risk: "medium" },
    { domain: "onesignal.com",            name: "OneSignal",                   type: "Push Notif.",      risk: "medium" },
    { domain: "clearbit.com",             name: "Clearbit",                    type: "Enrichment",       risk: "medium" },
    { domain: "tealiumiq.com",            name: "Tealium iQ",                  type: "Tag Manager",      risk: "medium" },
    { domain: "tiqcdn.com",               name: "Tealium CDN",                 type: "Tag Manager",      risk: "medium" },
    { domain: "ensighten.com",            name: "Ensighten",                   type: "Tag Manager",      risk: "medium" },
    { domain: "bizographics.com",         name: "LinkedIn Bizographics",       type: "B2B Tracker",      risk: "medium" },
    { domain: "bat.bing.com",             name: "Bing Ads Tracker",            type: "Ad Tracker",       risk: "high" },
    { domain: "clarity.ms",              name: "Microsoft Clarity",           type: "Session Replay",   risk: "high" },
    { domain: "c.clarity.ms",            name: "Clarity CDN",                 type: "Session Replay",   risk: "high" },
    { domain: "crazyegg.com",            name: "Crazy Egg",                   type: "Heatmap",          risk: "high" },
    { domain: "inspectlet.com",          name: "Inspectlet",                  type: "Session Replay",   risk: "high" },
    { domain: "kissmetrics.com",         name: "KissMetrics",                 type: "Analytics",        risk: "medium" },
    { domain: "woopra.com",              name: "Woopra",                      type: "Analytics",        risk: "medium" },
    { domain: "contentsquare.net",       name: "Contentsquare",               type: "Session Replay",   risk: "high" },
    { domain: "clicktale.net",           name: "ClickTale (Contentsquare)",   type: "Session Replay",   risk: "high" },
    { domain: "onetrust.com",            name: "OneTrust (CMP)",              type: "Consent Mgmt",     risk: "low" },
    { domain: "cookielaw.org",           name: "OneTrust Cookie Law",         type: "Consent Mgmt",     risk: "low" },
    { domain: "cookiebot.com",           name: "Cookiebot",                   type: "Consent Mgmt",     risk: "low" },
    { domain: "trustarc.com",            name: "TrustArc",                    type: "Consent Mgmt",     risk: "low" },
    { domain: "iubenda.com",             name: "iubenda",                     type: "Consent Mgmt",     risk: "low" },
    { domain: "siftscience.com",         name: "Sift Science",                type: "Fraud Detection",  risk: "medium" },
    { domain: "clarity.ms",             name: "Microsoft Clarity",           type: "Session Replay",   risk: "high" },
    { domain: "pendo.io",               name: "Pendo",                       type: "Product Analytics", risk: "medium" },
    { domain: "data.pendo.io",          name: "Pendo Data",                  type: "Product Analytics", risk: "medium" },
    { domain: "appcues.com",            name: "Appcues",                     type: "Product Analytics", risk: "medium" },
    { domain: "appcues.net",            name: "Appcues CDN",                 type: "Product Analytics", risk: "medium" },
    { domain: "gainsight.com",          name: "Gainsight",                   type: "CS Analytics",     risk: "medium" },
    { domain: "walkme.com",             name: "WalkMe",                      type: "DAP",              risk: "medium" },
    { domain: "mparticle.com",          name: "mParticle",                   type: "CDP",              risk: "medium" },
    { domain: "lytics.io",              name: "Lytics",                      type: "CDP",              risk: "medium" },
    { domain: "bloomreach.com",         name: "Bloomreach",                  type: "CDP",              risk: "medium" },
    { domain: "rudderstack.com",        name: "Rudderstack",                 type: "CDP",              risk: "medium" },
    { domain: "snowplow.io",            name: "Snowplow",                    type: "Analytics",        risk: "medium" },
    { domain: "klaviyo.com",            name: "Klaviyo",                     type: "Email Marketing",  risk: "medium" },
    { domain: "static.klaviyo.com",     name: "Klaviyo Static",              type: "Email Marketing",  risk: "medium" },
    { domain: "attentivemobile.com",    name: "Attentive",                   type: "SMS Marketing",    risk: "medium" },
    { domain: "yotpo.com",              name: "Yotpo",                       type: "Reviews/Loyalty",  risk: "low" },
    { domain: "bazaarvoice.com",        name: "Bazaarvoice",                 type: "Reviews",          risk: "low" },
    { domain: "drift.com",              name: "Drift",                       type: "Chat/Marketing",   risk: "medium" },
    { domain: "driftt.com",             name: "Drift CDN",                   type: "Chat/Marketing",   risk: "medium" },
    { domain: "salecycle.com",          name: "SaleCycle",                   type: "Abandonment",      risk: "high" },
    { domain: "ometria.com",            name: "Ometria",                     type: "Ecom Marketing",   risk: "medium" },
    { domain: "recaptcha.net",          name: "reCAPTCHA",                   type: "Bot Detection",    risk: "low" },
  ],

  fingerprinters: [
    { domain: "fingerprintjs.com",        name: "FingerprintJS",              type: "Fingerprinting",   risk: "high" },
    { domain: "fpnpmcdn.net",             name: "FingerprintJS CDN",           type: "Fingerprinting",   risk: "high" },
    { domain: "fpapi.io",                 name: "FingerprintJS API",           type: "Fingerprinting",   risk: "high" },
    { domain: "maxmind.com",              name: "MaxMind GeoIP",               type: "IP Geolocation",   risk: "medium" },
    { domain: "ipdata.co",                name: "IPData",                      type: "IP Geolocation",   risk: "medium" },
    { domain: "ipinfo.io",                name: "IPInfo",                      type: "IP Geolocation",   risk: "medium" },
    { domain: "iovation.com",             name: "iovation (TransUnion)",       type: "Device ID",        risk: "high" },
    { domain: "threatmetrix.com",         name: "LexisNexis ThreatMetrix",     type: "Device ID",        risk: "high" },
    { domain: "crwdcntrl.net",            name: "Lotame Crowd Control",        type: "DMP",              risk: "high" },
    { domain: "adsymptotic.com",          name: "Lotame",                      type: "Fingerprinting",   risk: "high" },
  ],

  cosmeticSelectors: [
    "[id*='ad-']","[class*='ad-']","[id*='-ad']","[class*='-ad']",
    "[id*='ads-']","[class*='ads-']","[id*='advert']","[class*='advert']",
    "[id*='banner']","[class*='banner']","[id*='sponsor']","[class*='sponsor']",
    "[class*='promo']","[id*='promo']","[class*='outbrain']","[class*='taboola']",
    "[class*='mgid']","[class*='revcontent']","[class*='criteo']","[class*='native-ad']",
    "iframe[src*='doubleclick']","iframe[src*='adnxs']","iframe[src*='taboola']",
    "iframe[src*='outbrain']","iframe[src*='criteo']","iframe[src*='googlesyndication']",
    "div[data-google-query-id]",".adsbygoogle","[class*='google-ad']","[id*='google-ad']",
    "[class*='popup']","[id*='popup']","[class*='overlay'][class*='modal']",
    "[class*='newsletter-modal']","[class*='cookie-banner']","[class*='sticky-ad']",
    "[class*='interstitial']","[class*='ad-slot']","[id*='ad-slot']",
    "[class*='dfp']","[id*='dfp']","[class*='prebid']","[class*='gpt-ad']",
    "ins.adsbygoogle","div[id^='div-gpt-ad']","div[id^='dfp-ad']",
    "[data-ad-unit]","[data-ad-slot]","[data-adunit]",
    "[class*='advertisement']","[id*='advertisement']",
  ],

  siteProfiles: {
    "reddit.com":      { ads: ["googlesyndication.com","adnxs.com","moatads.com","triplelift.com","openx.net"],           trackers: ["google-analytics.com","segment.io","hotjar.com","amplitude.com"] },
    "cnn.com":         { ads: ["doubleclick.net","outbrain.com","taboola.com","rubiconproject.com","pubmatic.com"],        trackers: ["chartbeat.com","scorecardresearch.com","omtrdc.net","demdex.net","googletagmanager.com"] },
    "forbes.com":      { ads: ["doubleclick.net","criteo.com","rubiconproject.com","indexexchange.com","media.net"],      trackers: ["google-analytics.com","quantserve.com","addthis.com","bluekai.com","hotjar.com"] },
    "msn.com":         { ads: ["advertising.com","media.net","adnxs.com","adsrvr.org","bidswitch.net"],                   trackers: ["google-analytics.com","omtrdc.net","facebook.net","clarity.ms"] },
    "dailymail.co.uk": { ads: ["doubleclick.net","openx.net","pubmatic.com","criteo.com","taboola.com"],                  trackers: ["scorecardresearch.com","chartbeat.com","hotjar.com","googletagmanager.com"] },
    "buzzfeed.com":    { ads: ["googlesyndication.com","criteo.com","taboola.com","triplelift.com"],                      trackers: ["google-analytics.com","segment.io","amplitude.com","facebook.net"] },
    "huffpost.com":    { ads: ["doubleclick.net","rubiconproject.com","outbrain.com","pubmatic.com"],                     trackers: ["scorecardresearch.com","omtrdc.net","demdex.net","chartbeat.com"] },
    "nytimes.com":     { ads: ["doubleclick.net","googlesyndication.com","indexexchange.com","rubiconproject.com"],       trackers: ["google-analytics.com","chartbeat.com","scorecardresearch.com","googletagmanager.com"] },
    "theguardian.com": { ads: ["googlesyndication.com","openx.net","rubiconproject.com","sovrn.com"],                     trackers: ["google-analytics.com","chartbeat.com","hotjar.com","segment.io"] },
    "bbc.com":         { ads: ["googlesyndication.com","doubleclick.net","rubiconproject.com"],                           trackers: ["chartbeat.com","scorecardresearch.com","google-analytics.com"] },
    "yahoo.com":       { ads: ["advertising.com","ads.yahoo.com","media.net","doubleclick.net","adnxs.com"],              trackers: ["google-analytics.com","quantserve.com","omtrdc.net","demdex.net"] },
    "amazon.com":      { ads: ["amazon-adsystem.com","advertising.amazon.com","aax-us-east.amazon-adsystem.com"],         trackers: ["google-analytics.com","googletagmanager.com","scorecardresearch.com"] },
    "walmart.com":     { ads: ["doubleclick.net","criteo.com","amazon-adsystem.com"],                                     trackers: ["google-analytics.com","googletagmanager.com","segment.io","hotjar.com"] },
    "ebay.com":        { ads: ["doubleclick.net","adnxs.com","criteo.com","rubiconproject.com"],                          trackers: ["google-analytics.com","chartbeat.com","scorecardresearch.com"] },
    "default":         { ads: ["googlesyndication.com","doubleclick.net","adnxs.com","taboola.com","criteo.com","rubiconproject.com"], trackers: ["google-analytics.com","googletagmanager.com","facebook.net","hotjar.com","segment.io"] },
  },
};

window.ALL_BLOCKED = [
  ...BLOCKLIST.adNetworks,
  ...BLOCKLIST.trackers,
  ...BLOCKLIST.fingerprinters,
];

window.checkURL = function(urlStr) {
  try {
    const host = new URL(urlStr.startsWith('http') ? urlStr : 'https://' + urlStr).hostname.replace(/^www\./, '');
    return window.ALL_BLOCKED.find(e => host === e.domain || host.endsWith('.' + e.domain)) || null;
  } catch { return null; }
};

window.getSiteProfile = function(hostname) {
  const clean = hostname.replace(/^www\./, '');
  if (BLOCKLIST.siteProfiles[clean]) return BLOCKLIST.siteProfiles[clean];
  const partial = Object.keys(BLOCKLIST.siteProfiles).find(k => clean.endsWith(k) || k.endsWith(clean));
  return BLOCKLIST.siteProfiles[partial] || BLOCKLIST.siteProfiles['default'];
};
